---
jobs:
- name: deploy-production
  plan:
  - get: cg-docs-source
    trigger: true
  - put: cloud-gov-production
    params:
      manifest: cg-docs-source/manifest.yml
      path: cg-docs-source
      current_app_name: docs
 
resources:
- name: cg-docs-source
  type: git
  source:
    uri: {{cg-docs-git-url}}
    branch: {{cg-docs-branch}}

- name: cloud-gov-production
  type: cf
  source:
    api: {{cf-api-url-production}}
    username: {{cf-deploy-username-production}}
    password: {{cf-deploy-password-production}}
    organization: {{cf-organization}}
    space: {{cf-space}}
    skip_cert_check: false
